### ISSUE TITLE
L21 dimmer showing as unsupported

### ISSUE THREAD

**Issue by simoncavell** [AdyRock/com.lightwaverf.smartseries#4]
Hi Adrian,

I have been unable to get my L21 to work, the unsupported log shows:

    "device": {
      "productCode": "L21MK2",
      "device": "dimmer",
      "desc": "Smart Dimmer",
      "type": "lwrfTwoWay_v2",
      "cat": "Lighting",
      "gen": 2,
      "identify": "Yes",
      "reset": "Yes",
      "upgrade": "Yes",
      "diagnostics": "Yes",
      "periodOfBroadcast": "Yes",
      "rgbColor": "Yes",
      "switch": "Yes",
      "dimLevel": "Yes",
      "dimSetup": "Yes",
      "protection": "Yes",
      "power": "Yes",
      "energy": "Yes",
      "bulbSetup": "Yes"
    }

I have uninstalled and reinstalled your app with the same result.  Any advice appreciated.

Cheers,

Simon

**Comment by AdyRock** [comment]
Hi Simon, Sorry for the delay but only just seen your message. I need to investigate why I'm not getting notified of new issues.
I am guessing it is because LW have added the MK2 on the end of the productCode.
I am about to update the app ready for Homey V3 so I will add a fix at the same time. Hopefully that will be done this weekend so Athom might publish it early next week (provide they are not swamped by all the devs updating their apps at the same time).

Best regards,
Adrian.

**Comment by simoncavell** [comment]
That's great, thanks Adrian, I'll try the update when available and let you know how I get on.
Cheers,
Simon

**Comment by AdyRock** [comment]
I got home early today and jumped on the PC so I have pushed a beta version (1.1.4) and submitted it to Athom this evening. That should fix the MK2 issue, so hopefully they will publish it tomorrow. 

It also fixes the power reporting of dimmers and sockets so they update properly.

Hope it solves the issue for you.

**Comment by simoncavell** [comment]
The 1.1.4 beta was made available tonight and my dimmer is now working perfectly, thanks for the speedy response and fix.
Cheers,
Simon
